name: hspec-subject

license: MIT
copyright: (c) 2018 Simon Hengel
author: Simon Hengel <sol@typeful.net>
maintainer: Simon Hengel <sol@typeful.net>

ghc-options: -Wall

dependencies:
  - base == 4.*
  - hspec == 2.*
  - haskell-src-meta

library:
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec-subject
